server:
  port:
    8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      username: customer-service-db
      password: customer-service-db
      authentication-database: admin
