server:
  port:
    8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
      username: customer_service_user
      password: customer_service_pwd
      authentication-database: admin
