server:
  port:
    8050
spring:
  datasource:
    url: jdbc:postgresql://localhost:5100/product
    username: product_service_user
    password: product_service_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    location: classpath:db/migration/postgresql
    user: product_service_user
    password: product_service_pwd
  application:
    name: product-service
