version: '3.8'

services:
  customer_service:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - customer_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "customer_service_user"
      MONGO_INITDB_ROOT_PASSWORD: "customer_service_pwd"
    networks:
      - application_network

  product_service:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5100:5432"
    volumes:
      - product_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "product_service_user"
      POSTGRES_PASSWORD: "product_service_pwd"
      POSTGRES_DB: "product"
    networks:
      - application_network

volumes:
  customer_db:
  product_db:

networks:
  application_network:
    driver: bridge